# Generated by Django 4.1.3 on 2022-11-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insmooficina',
            name='Descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='insumocomputacion',
            name='Descripcion',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='Observaciones',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
