# Generated by Django 4.1.3 on 2022-12-05 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminAPP', '0002_alter_insmooficina_descripcion_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
        migrations.AlterField(
            model_name='insmooficina',
            name='Codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='insmooficina',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='insmooficina',
            name='Stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='insumocomputacion',
            name='Codigo',
            field=models.IntegerField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='insumocomputacion',
            name='Descripcion',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='Codigo',
            field=models.IntegerField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='Numero_de_chasis',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='Observaciones',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='Patente',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='registrovehiculo',
            name='Tipo',
            field=models.CharField(choices=[['Sedan', 'Sedan'], ['Hachback', 'Hachback'], ['Camioneta', 'Camioneta'], ['Furgoneta', 'Furgoneta']], max_length=100),
        ),
    ]
